-- 001_consolidated_schema.sql — clpr consolidated PostgreSQL schema (D-052 P1)
--
-- Fresh-database consolidation of the SQLite migration chain 001-007 plus the
-- worker-created transcript_signal_candidates table, ported under the
-- operator-approved rename map (see app/docs/naming-map.md).
--
-- Dialect rules applied (per the P1 brief):
--   INTEGER PRIMARY KEY -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--     (BY DEFAULT, not ALWAYS: the P2 consolidation script inserts explicit ids
--      and fixes sequences afterward with setval).
--   REAL -> double precision; TEXT stays text.
--   ISO-8601 timestamps REMAIN text (port fidelity — recency merge compares
--   ISO strings).
--   CHECK constraints ported verbatim; UNIQUE constraints and indexes ported.
--   IFNULL -> COALESCE in idx_llm_signal_candidates_unique (approved dialect
--   translation, semantically identical).
--
-- Deliberately EXCLUDED: candidates_v2 — empty vestige of the failed 005
-- re-run diagnosed in D-027; not a design object (see naming-map.md).

-- ---------------------------------------------------------------------------
-- recordings (was: vods)
-- ---------------------------------------------------------------------------
CREATE TABLE recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path text NOT NULL UNIQUE,
    session_label text NOT NULL, -- e.g. '2026-07-20' — groups multi-segment days
    duration_s double precision,
    ingested_at text NOT NULL, -- ISO8601, set by the worker at insert time
    state text NOT NULL DEFAULT 'ingested'
        CHECK (state IN ('ingested','transcribed','detected','done')),
    -- poison_reviewed: a recording's poison sidecar has NOT been generated just
    -- because poison_regions has zero rows for it. This column is the explicit
    -- "someone reviewed this recording for poison regions" marker.
    -- Absence (0) means detection MUST refuse to run.
    poison_reviewed integer NOT NULL DEFAULT 0,
    display_name text -- NEW in PG (approved): nullable human-facing label
);

-- ---------------------------------------------------------------------------
-- poison_regions (unchanged name)
-- ---------------------------------------------------------------------------
CREATE TABLE poison_regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    start_s double precision NOT NULL,
    end_s double precision NOT NULL,
    source text NOT NULL, -- 'safe_mode' | 'manual' | 'incident'
    reason text NOT NULL
);

-- ---------------------------------------------------------------------------
-- trigger_beats (was: beats)
-- ---------------------------------------------------------------------------
CREATE TABLE trigger_beats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT REFERENCES recordings(id), -- nullable (port fidelity)
    ts_utc text NOT NULL, -- when the beat was marked, ISO8601
    note text,
    offset_s double precision, -- recording-relative seconds of the beat/trigger point; nullable
    source text NOT NULL DEFAULT 'manual' -- vocabulary enforced in code (ported as-is from SQLite)
);

-- ---------------------------------------------------------------------------
-- transcript_segments (unchanged name)
-- ---------------------------------------------------------------------------
CREATE TABLE transcript_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    start_s double precision NOT NULL,
    end_s double precision NOT NULL,
    text text NOT NULL
);

-- ---------------------------------------------------------------------------
-- audio_energy_buckets (was: audio_energy)
-- ---------------------------------------------------------------------------
CREATE TABLE audio_energy_buckets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    start_s double precision NOT NULL,
    end_s double precision NOT NULL,
    loudness_lufs double precision NOT NULL,
    UNIQUE (recording_id, start_s, end_s)
);

-- ---------------------------------------------------------------------------
-- llm_signal_candidates (was: transcript_signal_candidates)
-- ---------------------------------------------------------------------------
CREATE TABLE llm_signal_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    start_s double precision NOT NULL,
    end_s double precision NOT NULL,
    category text NOT NULL,
    reason text NOT NULL,
    confidence double precision NOT NULL,
    source text NOT NULL,
    trigger_offset_s double precision,
    run_id text NOT NULL,
    created_at text NOT NULL
);

-- was: idx_tsc_unique. IFNULL -> COALESCE (approved dialect translation).
CREATE UNIQUE INDEX idx_llm_signal_candidates_unique
    ON llm_signal_candidates (recording_id, start_s, end_s, category, source, (COALESCE(trigger_offset_s, -1)));

-- ---------------------------------------------------------------------------
-- chat_raw (unchanged name)
-- ---------------------------------------------------------------------------
CREATE TABLE chat_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_label text NOT NULL,
    ts_utc text NOT NULL,
    author text NOT NULL,
    text text NOT NULL,
    captured_by_run text NOT NULL
);

-- ---------------------------------------------------------------------------
-- chat_messages (unchanged name)
-- ---------------------------------------------------------------------------
CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    offset_s double precision NOT NULL,
    author text NOT NULL,
    text text NOT NULL,
    UNIQUE (recording_id, offset_s, author, text)
);

-- ---------------------------------------------------------------------------
-- clip_candidates (was: candidates)
-- ---------------------------------------------------------------------------
CREATE TABLE clip_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    start_s double precision NOT NULL,
    end_s double precision NOT NULL,
    score double precision,
    signal_audio double precision,
    signal_transcript double precision,
    signal_chat double precision,
    signal_beat_boost double precision,
    state text NOT NULL DEFAULT 'candidate'
        CHECK (state IN ('candidate','approved','rejected','poisoned','maybe')),
    created_by_run text NOT NULL,
    created_at text NOT NULL,
    UNIQUE (recording_id, start_s, end_s)
);

-- ---------------------------------------------------------------------------
-- clips (unchanged name)
-- ---------------------------------------------------------------------------
CREATE TABLE clips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES clip_candidates(id),
    file_path text NOT NULL,
    duration_s double precision NOT NULL,
    state text NOT NULL DEFAULT 'rendered'
        CHECK (state IN ('rendered','published')),
    created_by_run text NOT NULL,
    created_at text NOT NULL,
    drive_synced_at text,
    drive_sync_path text,
    UNIQUE (candidate_id)
);

-- ---------------------------------------------------------------------------
-- schema_migrations — apply-once ledger (same discipline as D-027's SQLite ledger)
-- ---------------------------------------------------------------------------
CREATE TABLE schema_migrations (
    filename text PRIMARY KEY,
    applied_at text NOT NULL -- ISO8601 UTC
);

-- ---------------------------------------------------------------------------
-- Grants for the app role (role already provisioned; no role creation here)
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_rw;

-- ---------------------------------------------------------------------------
-- Record this migration in the ledger
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (filename, applied_at)
VALUES ('001_consolidated_schema.sql', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
