-- 003_post_kits.sql — D-061/D-062: THE POST KIT.
--
-- The system SUGGESTS copy. It never burns text into video and it never posts.
-- Everything here is additive: three new tables plus ONE new column on
-- clip_candidates. No existing column is altered, retyped or rewritten, so
-- every existing reader keeps working unchanged.
--
-- IMPORTANT FORMATTING CONSTRAINT: the live applicator is
-- app/workers/migrations.py, which splits this file on the semicolon
-- character. Therefore NO semicolon may appear inside a comment or a string
-- literal in this file. Every semicolon below terminates a real statement.
-- (The first draft of this very comment broke that rule twice, and only the
--  mechanical check caught it. A lesson in prose is a proxy for a check.)
--
-- WHAT IS STORED, AND WHY EACH PIECE EXISTS
--
-- 1. creator_profile — the GLOBAL channel profile (channel, handle, style,
--    do-nots). It is CHANNEL context, not speaker identity: the post lands on
--    his channel whoever is on screen, so it applies to every clip. Versioned,
--    exactly one active row.
--
-- 2. recording_context — the PER-RECORDING context, carrying the SUBJECT.
--    D-062 ruling 4, verbatim: "im not the subject of all videos ... the
--    mainooo video is a dj that is not me". subject_kind is NOT NULL with NO
--    DEFAULT on purpose: there is deliberately no way for a row to quietly
--    mean "me". A recording with NO row at all is treated by the worker as
--    subject unknown (never as the operator), and the prompt says so out loud.
--
-- 3. post_kits — one row per candidate per generation, VERSIONED. A regenerate
--    NEVER destroys a previous kit and NEVER destroys an operator edit: an
--    edit is its own row with origin='operator_edit', and from then on it is
--    authoritative (the worker refuses to deactivate it without an explicit
--    --force). Exactly one row per candidate is active, enforced by a partial
--    unique index rather than by convention.
--
-- 4. clip_candidates.post_kit_enabled — the per-clip generate toggle,
--    DEFAULT 1 (ON), so every pre-existing candidate inherits the ruled
--    default with no data rewrite.
--
-- THE RESEARCH CONSTRAINTS ARE ENFORCED AS CHECKS, NOT AS PROSE — BUT ONLY
-- AGAINST THE MACHINE. Every research gate below is written
-- "origin <> 'generated' OR <rule>", so it binds model output and is silent on
-- operator edits. The operator is the publish gate (D-002) and his own words
-- are law (charter 3.5): the schema must never refuse what he typed.
--   - hooks: 1..120 chars each (Instagram demotes majority-text reels, so the
--     on-video hook is ONE SHORT LINE)
--   - hashtags: at most 3 (Instagram caps at 5, and a 24.3M-post study
--     measured 31% FEWER views on posts carrying them)
--   - no em dash anywhere in generated copy (project rule for anything that
--     can reach a social platform)

-- ---------------------------------------------------------------------------
-- creator_profile — the GLOBAL profile block, versioned, one active row
-- ---------------------------------------------------------------------------
CREATE TABLE creator_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version integer NOT NULL CHECK (version >= 1),
    channel_name text,
    handle text,
    platforms text,      -- free text, e.g. 'instagram reels, tiktok, youtube shorts'
    style_notes text,    -- voice and tone the copy should sound like
    do_nots text,        -- hard avoids, stated plainly for the writer model
    extra_context text,
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_by text NOT NULL,  -- 'operator' or a worker run_id
    created_at text NOT NULL,  -- ISO8601 UTC, text (port fidelity with 001)
    UNIQUE (version)
);

-- At most ONE active profile, enforced by the database rather than by care.
CREATE UNIQUE INDEX idx_creator_profile_active ON creator_profile (is_active) WHERE is_active = 1;

-- ---------------------------------------------------------------------------
-- recording_context — PER-RECORDING context and the SUBJECT (D-062 ruling 4)
-- ---------------------------------------------------------------------------
CREATE TABLE recording_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_id BIGINT NOT NULL REFERENCES recordings(id),
    version integer NOT NULL CHECK (version >= 1),
    -- 'me' pulls the full global profile in as the speaker's own identity.
    -- 'other' REQUIRES subject_text describing who is actually on screen.
    -- There is no third value and no default: absence of a row is handled in
    -- code as unknown, never as 'me'.
    subject_kind text NOT NULL CHECK (subject_kind IN ('me', 'other')),
    subject_text text,
    context_notes text,  -- what this recording was, in the operator's words
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_by text NOT NULL,
    created_at text NOT NULL,
    UNIQUE (recording_id, version),
    -- Two facts, two columns, and the pairing is enforced: 'other' without a
    -- description would leave the writer model to invent who the person is.
    CONSTRAINT recording_context_subject_pairing CHECK (
        (subject_kind = 'other' AND subject_text IS NOT NULL AND btrim(subject_text) <> '')
        OR (subject_kind = 'me' AND subject_text IS NULL)
    )
);

CREATE UNIQUE INDEX idx_recording_context_active ON recording_context (recording_id) WHERE is_active = 1;

-- ---------------------------------------------------------------------------
-- post_kits — one row per candidate per generation, versioned, one active
-- ---------------------------------------------------------------------------
CREATE TABLE post_kits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES clip_candidates(id),
    version integer NOT NULL CHECK (version >= 1),
    -- 'generated' = the models wrote it. 'operator_edit' = the operator wrote
    -- it, and it outranks anything generated afterwards.
    origin text NOT NULL CHECK (origin IN ('generated', 'operator_edit')),
    is_active integer NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    -- For an operator edit, the version it was derived from, so history reads
    -- as a chain rather than as a pile.
    edited_from_version integer,

    -- PRODUCT 1: on-video text. THREE variants, deliberately spread along the
    -- concreteness axis (withheld / domain-named / payoff-named) rather than
    -- reworded, because the Upworthy meta-analysis of 8,977 headline
    -- experiments found 50.9% of headlines got WORSE when made more concrete
    -- and only 8.7% better, so covering the range beats guessing the point.
    hook_withheld text NOT NULL,
    hook_domain text NOT NULL,
    hook_payoff text NOT NULL,

    -- PRODUCT 3: the video caption (the post descriptor) plus MINIMAL hashtags.
    video_caption text NOT NULL,
    hashtags text[],

    -- A line the writer model quoted from the transcript, or NULL. The worker
    -- refuses to write a row whose quoted_line is not present VERBATIM in the
    -- transcript of the shipped window, so this column can only ever hold
    -- something that was really said.
    quoted_line text,

    -- PRODUCT 2: captions, as a real SRT built from the stored whisper
    -- segments and rebased to the clip's own t=0. NULL when the window holds
    -- no transcript segments at all (under-claim: no captions beats invented
    -- captions).
    srt_text text,
    srt_segment_count integer NOT NULL DEFAULT 0 CHECK (srt_segment_count >= 0),
    -- Which geometry witness the rebasing used. Selected from the clip's
    -- created_by_run, i.e. from WHICH RENDERER actually shipped the file.
    srt_basis text CHECK (srt_basis IS NULL OR srt_basis IN ('sidecar', 'formula')),
    srt_clip_t0_abs_s double precision,     -- absolute recording time of clip t=0
    srt_clip_duration_s double precision,   -- the clip's real measured duration

    -- The vision model's scene description, kept because it is the input the
    -- copy was derived from. Auditable after the fact.
    scene_description text,

    -- Context provenance: exactly which context layers this kit was written
    -- against. 'unknown' is a real, recordable state.
    subject_kind text CHECK (subject_kind IS NULL OR subject_kind IN ('me', 'other', 'unknown')),
    recording_context_version integer,
    profile_version integer,

    -- Model provenance.
    vision_model text,
    writer_model text,
    prompt_version text,
    vision_generation_id text,
    writer_generation_id text,
    vision_params text,  -- JSON text: model, fps, media_resolution, passthrough requested/accepted/dropped
    writer_params text,  -- JSON text: model, temperature, max_tokens
    -- 1 when the provider refused one or more quality passthrough parameters,
    -- so a kit that silently ran at provider defaults is queryable, not buried
    -- in a log line nobody reads.
    passthrough_degraded integer CHECK (passthrough_degraded IS NULL OR passthrough_degraded IN (0, 1)),

    created_by_run text NOT NULL,
    created_at text NOT NULL,

    UNIQUE (candidate_id, version),

    -- An operator edit must say what it came from.
    CONSTRAINT post_kits_edit_has_parent CHECK (
        origin <> 'operator_edit' OR edited_from_version IS NOT NULL
    ),

    -- RESEARCH GATES — machine only, never the operator (see the header).
    -- One short line: Instagram officially demotes reels that are majority
    -- text, and TikTok's own 5-10 words per second guidance puts a hook read
    -- in the first 2 seconds at 10-20 words MAXIMUM.
    CONSTRAINT post_kits_generated_hook_length CHECK (
        origin <> 'generated' OR (
            char_length(hook_withheld) BETWEEN 1 AND 120
            AND char_length(hook_domain) BETWEEN 1 AND 120
            AND char_length(hook_payoff) BETWEEN 1 AND 120
        )
    ),
    CONSTRAINT post_kits_generated_caption_length CHECK (
        origin <> 'generated' OR char_length(video_caption) BETWEEN 1 AND 600
    ),
    -- At most 3 hashtags. Hashtags are near-dead as reach.
    CONSTRAINT post_kits_generated_hashtag_cap CHECK (
        origin <> 'generated'
        OR hashtags IS NULL
        OR array_length(hashtags, 1) IS NULL
        OR array_length(hashtags, 1) <= 3
    ),
    -- No em dash in generated copy. chr(8212) is U+2014.
    CONSTRAINT post_kits_generated_no_em_dash CHECK (
        origin <> 'generated'
        OR strpos(
            hook_withheld || hook_domain || hook_payoff || video_caption
            || COALESCE(quoted_line, ''),
            chr(8212)
        ) = 0
    )
);

-- At most ONE active kit per candidate. This is what makes "the active kit" a
-- fact rather than a convention, and it is what an operator edit wins.
CREATE UNIQUE INDEX idx_post_kits_active ON post_kits (candidate_id) WHERE is_active = 1;

CREATE INDEX idx_post_kits_candidate ON post_kits (candidate_id);

-- ---------------------------------------------------------------------------
-- The per-clip generate toggle, DEFAULT ON (D-062 ruling 2).
-- Additive with a default, so every existing candidate row inherits 1 with no
-- data rewrite. The single ADD COLUMN form is deliberate: migrations.py guards
-- ADD COLUMN against a duplicate-column re-run, and a separate ADD CONSTRAINT
-- statement would not be covered by that guard.
-- ---------------------------------------------------------------------------
ALTER TABLE clip_candidates ADD COLUMN post_kit_enabled integer NOT NULL DEFAULT 1 CHECK (post_kit_enabled IN (0, 1));

-- ---------------------------------------------------------------------------
-- Grants for the app role. 001's ALTER DEFAULT PRIVILEGES only covers tables
-- created by the SAME role that ran 001, and this migration may be applied by
-- a different role, so the grants are stated explicitly here rather than
-- assumed. Charter gate 4: a contract change is a breaking change until every
-- consumer is swept.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON creator_profile, recording_context, post_kits TO app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;

-- ---------------------------------------------------------------------------
-- Record this migration in the ledger
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (filename, applied_at)
VALUES ('003_post_kits.sql', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
