-- 004_post_kit_requests.sql — the review surface's REGENERATE REQUEST ledger.
--
-- FORMATTING CONSTRAINT inherited from 003: the live applicator
-- app/workers/migrations.py splits this file on the semicolon character, so no
-- semicolon may appear inside any comment or string literal here. Every
-- semicolon below terminates a real statement.
--
-- WHY THIS EXISTS. 003_post_kits.sql gives the generator everything it needs,
-- and generate_post_kit.py is correctly the ONLY thing that writes a kit. But
-- the review surface has to be able to ask for a fresh one, and it must do
-- that WITHOUT spending money from a browser button and WITHOUT touching the
-- active kit. So a regenerate is recorded here as an intent, exactly the way
-- clip_candidates.post_kit_enabled records an intent, and the generator
-- consumes it. Nothing in this table ever alters a post_kits row.
--
-- THE OPERATOR-EDIT GUARD IS THE POINT. generate_post_kit.py refuses to
-- supersede an active operator edit unless a human passes --force, and n8n
-- must never pass it. force_over_operator_edit records that the operator
-- himself asked for exactly that, in the review UI, after an explicit
-- confirmation, so the worker can honour it without a human at a terminal and
-- without n8n ever being able to fabricate it.
--
-- OUTSTANDING IS AN INTEGER COMPARISON, NOT A CLOCK. A request records the
-- kit version that was active when it was made. It is outstanding while
-- COALESCE(MAX(post_kits.version), 0) for that candidate is still less than or
-- equal to that number. No timestamps are compared anywhere, so there is no
-- format, no timezone and no ISO-versus-space ordering trap (charter gate 21,
-- bought by a purge that never once fired).
--
-- CONTRACT FOR THE GENERATOR LANE, stated so it cannot be inferred wrongly:
--   1. A row with state 'requested' whose active_version_at_request is still
--      the newest version means a kit is owed for that candidate, EVEN IF one
--      already exists.
--   2. force_over_operator_edit = 1 is the operator's own confirmed --force.
--      A row with 0 must never supersede an active operator edit.
--   3. On success the worker sets state 'satisfied' and
--      satisfied_kit_version. On refusal or failure it sets state 'failed'
--      and writes the raw reason into error, verbatim, and writes NO post_kits
--      row (charter gate 9, a failed run persists nothing and reports loudly).
--   4. Until the worker does any of that, the review surface reports the
--      request as UNANSWERED. It never claims a failure it was not told about.

CREATE TABLE post_kit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES clip_candidates(id),
    -- The kit version that was active when the operator asked. 0 means there
    -- was no kit at all.
    active_version_at_request integer NOT NULL DEFAULT 0 CHECK (active_version_at_request >= 0),
    force_over_operator_edit integer NOT NULL DEFAULT 0 CHECK (force_over_operator_edit IN (0, 1)),
    state text NOT NULL DEFAULT 'requested' CHECK (state IN ('requested', 'satisfied', 'failed')),
    -- The raw failure reason, quoted verbatim from whatever produced it.
    error text,
    satisfied_kit_version integer,
    requested_by text NOT NULL,
    requested_at text NOT NULL,
    -- A failed request must say why. A state that carries no reason is a
    -- failure the operator cannot act on.
    CONSTRAINT post_kit_requests_failed_has_reason CHECK (
        state <> 'failed' OR (error IS NOT NULL AND btrim(error) <> '')
    ),
    CONSTRAINT post_kit_requests_satisfied_has_version CHECK (
        state <> 'satisfied' OR satisfied_kit_version IS NOT NULL
    )
);

CREATE INDEX idx_post_kit_requests_candidate ON post_kit_requests (candidate_id, id DESC);

-- ---------------------------------------------------------------------------
-- Grants for the app role. 001 set ALTER DEFAULT PRIVILEGES for the role that
-- ran it, which does not necessarily cover a table created later by a
-- different role, so the grant is explicit rather than assumed.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON post_kit_requests TO app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;

-- ---------------------------------------------------------------------------
-- Record this migration in the ledger
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (filename, applied_at)
VALUES ('004_post_kit_requests.sql', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
